### ISSUE TITLE
Clarify support for Centos8

### ISSUE THREAD

**Issue by david22swan** [puppetlabs/iac#335]
As of the last release of the Puppet agent support for CentOS 8 has been dropped. However it is not fully clear if it has been dropped in favor of CentOS Stream 8 or just fully dropped.
This will need to be clarified and then depending on which answer is given we will have to remove CentOS 8 from the metadata and CI pipeline, or clarify within the metadata that we now support CentOS Stream 8 instead.

**Comment by david22swan** [comment]
1. https://github.com/puppetlabs/puppetlabs-accounts/pull/400
2. https://github.com/puppetlabs/puppetlabs-apache/pull/2219
3. https://github.com/puppetlabs/puppetlabs-apt/pull/1021
4. https://github.com/puppetlabs/puppetlabs-concat/pull/727
5. https://github.com/puppetlabs/puppetlabs-docker/pull/806
6. https://github.com/puppetlabs/puppetlabs-exec/pull/186
7. https://github.com/puppetlabs/puppetlabs-facter_task/pull/186
8. https://github.com/puppetlabs/puppetlabs-firewall/pull/1037
9. https://github.com/puppetlabs/puppetlabs-haproxy/pull/510
10. https://github.com/puppetlabs/puppetlabs-helm/pull/165

**Comment by chelnak** [comment]
Issue moved to [puppetlabs/content-and-tooling-team #8](https://github.com/puppetlabs/content-and-tooling-team/issues/8) via [**ZenHub**](https://www.zenhub.com/)
