### ISSUE TITLE
Certify new OS RedHat 9

### ISSUE THREAD

**Issue by david22swan** [puppetlabs/iac#338]
This is the ticket tracking the progress of rolling out RedHat 9 to each of our supported modules.

PreReq for this work

1) Puppet Agent has been released with RedHat 9 support

reference https://tickets.puppetlabs.com/browse/IAC-150 defining procedure for testing

**Modules that need support added:**

1. accounts
2. apache
3. concat
4. exec
5. facter_task
6. firewall
7. haproxy
8. ibm_installation_manager
9. inifile
10. java
11. java-ks
12. motd
13. mysql
14. package
15. postgresql
16. powershell
17. puppet-conf
18. reboot
19. satellite_pe_tools
20. service
21. stdlib
22. tagmail
23. tomcat
24. translate
25. vcsrepo
26. vsphere
27. websphere_application_server (review [IAC-15](https://tickets.puppetlabs.com/browse/IAC-15)) is this still an issue

**Comment by chelnak** [comment]
Issue moved to [puppetlabs/content-and-tooling-team #12](https://github.com/puppetlabs/content-and-tooling-team/issues/12) via [**ZenHub**](https://www.zenhub.com/)
